version: "3.8"

services:

  localstack:
    build:
      context: ./docker/localstack/
    image: snovault-localstack
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - SERVICES=sqs
      - LS_LOG=warn
    ports:
      - "4566:4566"
    volumes:
      - "./docker/localstack/create_localstack.sh:/docker-entrypoint-initaws.d/create_localstack.sh"

  postgres:
    build:
      context: ./docker/postgres/
    image: snovault-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  opensearch:
    build:
      context: ./docker/opensearch/
    image: snovault-opensearch
    environment:
      - "discovery.type=single-node"
      - "node.name=opensearch-node1"
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - "./config/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  loader:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: snovault-pyramid
    volumes:
      - ".:/snovault"
      - "/snovault/src/snovault.egg-info"
    command: load-development
    depends_on:
      - postgres

  pyramid:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: snovault-pyramid
    volumes:
      - ".:/snovault"
      - "/snovault/src/snovault.egg-info"
    command: /scripts/pyramid/run-development.sh
    ports:
      - "6543:6543"
    depends_on:
      - loader

  create-mapping:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: igvfd-pyramid
    volumes:
      - ".:/snovault"
      - "/snovault/src/snovault.egg-info"
    command: /scripts/pyramid/run-create-mapping.sh
    depends_on:
      - pyramid

  invalidation-service:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: snovault-pyramid
    volumes:
      - ".:/snovault"
      - "/snovault/src/snovault.egg-info"
    command: python src/snovault/services/invalidation.py
    depends_on:
      - pyramid

  indexing-service:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: snovault-pyramid
    volumes:
      - ".:/snovault"
      - "/snovault/src/snovault.egg-info"
    command: python src/snovault/services/indexing.py
    depends_on:
      - pyramid
