version: "3.8"

services:

  localstack:
    build:
      context: ./docker/localstack/
    image: snovault-localstack
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - SERVICES=sqs
      - LS_LOG=warn
    ports:
      - "4566:4566"
    volumes:
      - "./docker/localstack/create_localstack.sh:/docker-entrypoint-initaws.d/create_localstack.sh"

  postgres:
    build:
      context: ./docker/postgres/
    image: snovault-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  pyramid:
    build:
      context: .
      dockerfile: ./docker/pyramid/Dockerfile
    image: snovault-pyramid
    environment:
      - LOCALSTACK_ENDPOINT_URL=http://localstack:4566
      - TRANSACTION_QUEUE_URL=http://localstack:4566/000000000000/transaction-queue
      - INVALIDATION_QUEUE_URL=http://localhost:4566/000000000000/invalidation-queue
      - TRANSACTION_DEAD_LETTER_QUEUE_URL=http://localhost:4566/000000000000/transaction-dead-letter-queue
      - INVALIDATION_DEAD_LETTER_QUEUE_URL=http://localhost:4566/000000000000/invalidation-dead-letter-queue
    volumes:
      - ".:/snovault"
      - "/snovault/src/snovault.egg-info"
    command: pytest -rf -m "not indexing and not bdd"
    ports:
      - "6543:6543"
    depends_on:
      - postgres
