version: 2.1

workflows:
  snovault-tests:
    jobs:
      - lint
      - snovault-pytest:
          requires:
            - lint
      - snovault-pytest-indexer:
          requires:
            - lint
      - snovault-check-opensearch-mappings:
          requires:
            - lint


jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/snovault
    steps:
      - checkout
      - run: pip install pre-commit==2.17.0
      - run: pre-commit run --all-files

  snovault-pytest:
    machine:
      image: ubuntu-2004:2023.04.2
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/snovault
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: Set folder permissions for mounted volume
          command: |
              sudo useradd -u 1444 snovault
              sudo usermod -a -G snovault circleci
              sudo chown -R circleci:snovault ./
      - run:
          name: Run tests
          command: |
              docker-compose -f docker-compose.test.yml up --exit-code-from pyramid

  snovault-pytest-indexer:
    machine:
      image: ubuntu-2004:2023.04.2
      docker_layer_caching: true
    resource_class: large
    working_directory: ~/snovault
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose.test-indexer.yml build
      - run:
          name: Set folder permissions for mounted volume
          command: |
              sudo useradd -u 1444 snovault
              sudo usermod -a -G snovault circleci
              sudo chown -R circleci:snovault ./
      - run:
          name: Run tests
          command: |
              docker-compose -f docker-compose.test-indexer.yml up --exit-code-from indexer-tests

  snovault-check-opensearch-mappings:
    machine:
      image: ubuntu-2004:2023.04.2
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/snovault
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: |
              docker-compose -f docker-compose.yml build
      - run:
          name: Set folder permissions for mounted volume
          command: |
              sudo useradd -u 1444 snovault
              sudo usermod -a -G snovault circleci
              sudo chown -R circleci:snovault ./
      - run:
          name: Check Opensearch mappings for diff
          command: |
              docker-compose run pyramid /scripts/pyramid/diff-opensearch-mappings.sh
